### ISSUE TITLE
No option to disable night fog colors

### ISSUE THREAD

**Issue by 22luminary** [IMB11/Fog#37]
There should be an option to disable fog switching colors at night. I think this mod looks amazing but the blue fog at night bothers me too much!

**Comment by mdaole** [comment]
Agreed! I love the daytime and rain fog, but the I'd like my nights to be very dark.

**Comment by Steveplays28** [comment]
Hi,I think the issue is that your fog definitions are out-of-date.
We fixed the nighttime fog colors a while back, but our update screen doesn't have an option to auto-update the fog colors yet. IMB wants to work on this in the near future.

Could you please update your fog definitions, by deleting them and letting Fog recreate them (located at `config/fog/fog_definitions`)?

Most nighttime fog colors that I tested are dark, as they should be. I just fixed the badlands nighttime fog colors as well.
Feel free to reopen the issue if there are any nighttime fog colors that look too bright to you.

**Comment by Steveplays28** [comment]
I've also reduced the brightness the beach and default nighttime fog colors, they're now almost pitch black.

**Comment by mdaole** [comment]
Thank you for your work on this!
I think the issue seems to be that config/fog/fog_definitions doesn't update, even when that folder or the entire config/fog folder is deleted. I just tried doing both and both times the fog update menu came up when I restarted Minecraft, but the fog definitions folder only contains pack.mcmeta and README.txt, nothing else.

![image](https://github.com/user-attachments/assets/57c7fd79-7197-41ca-800b-4f3c831a4b4f)

I also just tested from a complete brand new install of Minecraft on Modrinth with just Fog installed and on very first startup, the fog_definitions folder doesn't have anything besides those two files. Deleting the folders again also still had the same result.

Here's the config folder and the logs if it'd be helpful for debugging
[config.zip](https://github.com/user-attachments/files/17438584/config.zip)
[2024-10-18-2.log.gz](https://github.com/user-attachments/files/17438608/2024-10-18-2.log.gz)

**Comment by Steveplays28** [comment]
Yeah that's also an issue currently @mdaole, though it means that the fog definitions from the JAR will always be used, since there aren't any unpacked files to load instead.
IMB is going to take a look at this in the near future.

**Comment by Steveplays28** [comment]
The changes I mentioned have been released in Fog [`v1.5.0`](https://github.com/IMB11/Fog/releases/latest).

**Comment by mdaole** [comment]
Love it, thank you
